### ISSUE TITLE
WS timeout too low

### ISSUE THREAD

**Issue by siedi** [jjlawren/sonos-websocket#7]
Hi, 
I'm using homeassistant  which uses your library for the Sonos integration, especially the new announcement feature. In general it works, some of my Sonos play 1 just have a weak wifi connection, which leads to connection timeouts from time to time. 
From what I can see, you have hardcoded the timeout to 3 secs.
Is there any reason for the 3 sec? Do you mind increasing it to 5sec, or maybe even expose it, so it can be tweaked in home assistant?
Thanks
Siedi

**Comment by jjlawren** [comment]
Have you done any testing to validate that increasing the timeout would make any meaningful difference?

**Comment by siedi** [comment]
Actually, the timeout is not the issue. It is really due to a weak wifi connected. I added some retries to the code (in a hakish way), but even that doesn't help at that moment. Next day, it works again smoothly. I think we can close the issue.

**Comment by ciaranj** [comment]
I've just run into this, for me, on my perhaps aged play:1 units when they're already playing something they somestimes take longer than 3 seconds to create the web socket connection. I've linked a [video](https://www.youtube.com/watch?v=oC6gXhf65es)  that demonstrates a series of failures followed by a success when I increase the timeout through a supplied argument (pull request incoming!) I consume this library via home assistant, so my plan would be for this argument to be included then allow it to be a tunable argument in hass core if you're agreeable.
